# Welcome to Jekyll!
title: Matej Kramny
url: https://matej.me
baseurl: /

# Sass setting
sass:
    sass_dir: _sass
    style:    compressed

# Custom Values
lang: en                    # html lang
open: true                  # open or close your site
force_https: true           # force http to https
date_format: "%Y-%m-%d"     # date format
google_analytics:           # your google analytics
theme_color: "#000"      # your favorite theme color